name: Build App Windows (Nuitka)

# Kích hoạt quy trình này khi có code mới đẩy lên nhánh main
# Hoặc cho phép bấm chạy thủ công (workflow_dispatch)
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    # Sử dụng máy chủ Windows mới nhất của GitHub
    runs-on: windows-latest

    steps:
    - name: Tải mã nguồn về máy chủ
      uses: actions/checkout@v4

    - name: Cài đặt Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # Lưu cache pip để các lần build sau nhanh hơn

    - name: Cài đặt thư viện (Dependencies)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Biên dịch bằng Nuitka
      run: |
        python -m nuitka --mingw64 --standalone --enable-plugin=pyside6 --windows-console-mode=disable --windows-icon-from-ico=logo.ico main.py

    - name: Đóng gói và Lưu kết quả (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: Tool_BangGia_Pro_Windows
        # Nuitka mode standalone sẽ tạo ra thư mục .dist, ta sẽ upload thư mục này
        path: main.dist/