name: Build Python to EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Sử dụng Windows để build file .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name AUTO-PRICE AUTO-PRICE.py
      shell: cmd  # Sử dụng CMD để đảm bảo tương thích với Windows

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: AUTO-PRICE-executable
        path: dist/AUTO-PRICE.exe
